// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh_rqPu2XSrvjp86dkoss4ji9z47NRgR0',
    appId: '1:873808093366:web:7d998a9d70a12e14b34617',
    messagingSenderId: '873808093366',
    projectId: 'resq-net-hackathon',
    authDomain: 'resq-net-hackathon.firebaseapp.com',
    storageBucket: 'resq-net-hackathon.firebasestorage.app',
    measurementId: 'G-G95ZM1X1H9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwVyW1PlNDtSw1-fmLnmnWBFG4SlEueRI',
    appId: '1:873808093366:android:369821056bb9aa62b34617',
    messagingSenderId: '873808093366',
    projectId: 'resq-net-hackathon',
    storageBucket: 'resq-net-hackathon.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh_rqPu2XSrvjp86dkoss4ji9z47NRgR0',
    appId: '1:873808093366:web:e0d140a4e3393e33b34617',
    messagingSenderId: '873808093366',
    projectId: 'resq-net-hackathon',
    authDomain: 'resq-net-hackathon.firebaseapp.com',
    storageBucket: 'resq-net-hackathon.firebasestorage.app',
    measurementId: 'G-D0ZWVQKSN5',
  );
}
